[package]
name = "lidarserv-colorization"
version = "0.1.0"
edition = "2024"

[dependencies]
las = "0.9"
image = "0.25.6"
lidarserv-common.path = "../lidarserv-common"
log = "0.4.27"
rosrust = "0.9.12"
simple_logger = "5.0"
anyhow = "1.0.98"
clap = { version = "4.5.41", features = ["derive"] }
tokio = { version = "1.46.1", features = ["full"] }
ctrlc = "3.4.7"
console = "0.16.0"